### PR TITLE
adds yard opts for documentation and readme fixes

### PR DESCRIPTION
**Pull request by rebel-one**

### CODE REVIEW

**Comment by rebel-one** [comment]
@jaredcunha-usds Can you do a quick review? It's mostly cosmetic changes but I changed a few things on readme.

**Comment by jaredcunha-usds** [comment]
Looks find to me. Do you think we need to bump the version number?

Also, that AWS test is failing. Do you know what's up with that?

**Comment by rebel-one** [comment]
We don't need to up the version but whenever I change something I tend to up it but up to you. I can change it back, it's mostly documentation changes only.

On the AWS testing that's not an issue. Already checked with Charles. 

Do you want me to undo the version bump?

**Comment by jaredcunha-usds** [comment]
@rebel-one You can leave it. I was just just curious if this constitutes a 'patch.' I'm going to be bumping this to `1.15.0` with the new nav anyway.

**Pull request merged**
